### ISSUE TITLE
Set-climate-temperature: slider is only in °C

### ISSUE THREAD

**Issue by raphmur** [tesla-local-control/tesla_ble_mqtt_core#101]
But `mqtt-listen.sh` accepts also a °F value
-> Maybe change the range using the timezone in env files?

**Comment by baylanger** [comment]
> But `mqtt-listen.sh` accepts also a °F value -> Maybe change the range using the timezone in env files?
>
Apprently there's [no need](https://github.com/home-assistant/frontend/blob/dc79fc2919d836ae28ce0c065aacd6ef52f47dc7/src/common/entity/sensor_icon.ts#L19) to specify the icon for this type of entity.

Also conversion between F and C is automatic to your locale. What's difficult is to know if the car is configured to use F or C.

**Comment by baylanger** [comment]
https://github.com/tesla-local-control/tesla_ble_mqtt_core/pull/110
https://github.com/tesla-local-control/tesla-local-control-addon/pull/101
https://github.com/tesla-local-control/tesla_ble_mqtt_docker/pull/44

**Comment by raphmur** [comment]
PR #110
