### ISSUE TITLE
Add support for coming per product "libproduct.sh"

### ISSUE THREAD

**Issue by baylanger** [tesla-local-control/tesla_ble_mqtt_core#16]
The goal is to move out from run.sh specific code to each product, put in a libproduct.sh file, and source if it's available.

Call a generic function available in both product `productInit()`

Once both products have their own libproduct.sh file, we can remove the if statement.

**Comment by raphmur** [comment]
What do you see specific? So far I see only the logging and env vars capture.

**Comment by raphmur** [comment]
[v0.1.0 release in addon](https://github.com/tesla-local-control/tesla-local-control-addon/releases/tag/v0.1.0)
[v0.1.0 release in docker](https://github.com/tesla-local-control/tesla_ble_mqtt_docker/releases/tag/v0.1.0)
