### ISSUE TITLE
Add new MQTT entity for set amps if already below 5a 

### ISSUE THREAD

**Issue by raphmur** [tesla-local-control/tesla_ble_mqtt_core#19]
Sending charge amps request below 5a is managed specifically with 2 commands: set to 5a, then below 5a
However, when periodically updating the charge current below 5a, this is going yoyo as the script will systematically bring it back up to 5a then again below...

Best thing would be to "know" which value was sent before, then do not double send if already below 5a...

It is much easier for me to manage in HA if I already sent a command below 5a and do not need to pass again through 5a.
I suggest to add a specific button "set charge amps below 5a", maybe under "diagnosis" category.

**Comment by epenet** [comment]
You dont need to send first to 5A, then again below 5A
- if current value is > 5A, send new value twice
- if current value is <= 5A, send new value just once

I think current docker version does this by always sending new value twice.

**Comment by raphmur** [comment]
yes this is what is in the core code (hardcoded):
- if < 5A, then 2 commands are sent: 5A then [your value]
- if >= 5A, only one command

This is fine, but not if your periodically update the charge current to values always below 5A, it goes yoyo:
5 > 2 > 5 > 3 > 5 > 2 > ...
Especially for solar charge...

PR #20 is to implement a specific entity / command that does not send 2 commands if below 5A...

@iainbullock, I wonder, can't we define an template button in HA that does this? instead of doing it in the addon...
