### ISSUE TITLE
Invalid topic tesla_ble/binary_sensor/presence

### ISSUE THREAD

**Issue by baylanger** [tesla-local-control/tesla_ble_mqtt_core#48]
With listen_to_mqtt in background, this has shown up a few times:

```
Invalid MQTT topic. Topic: tesla_ble/binary_sensor/presence Message: OFF
```

We probably just need to add a condition in the case) statement not to ignore them.

PR #52

**Comment by raphmur** [comment]
We are all clear in [v0.1.0](https://github.com/tesla-local-control/tesla_ble_mqtt_core/releases/tag/v0.1.0)
